### ISSUE TITLE
Question about classes

### ISSUE THREAD

**Issue by elefps** [devalab/DeepPocket#6]
Hello and congrats on your repo!

As I see at training segmentation, you have num_classes=1. That means that label=1 -> pocket and label->0 not pocket/?

**Comment by RishalAggarwal** [comment]
yup thats right

**Comment by mainguyenanhvu** [comment]
Hello @elefps have you re-run data preparation for a custom data? If yes, please help me. 

I am trying to use the instruction to prepare data for training a new classifier. 
I have stuck in make_types step because I can't find train.txt and test.txt files. 

Moreover, I have 4 questions:
1. If I want to add several pdb files to the available scPDB dataset, how can I complete it?
2. The instruction for preparing data only works for a single pdb file, does it? If not, I need to write a pipeline to wrap up it. 
3. How to prepare train.txt and test.txt files to run make_types.py?
4. Could you please show me which file/folder needed inputting from previous to each step?

I am tried on [this pdb](https://www.rcsb.org/structure/8BRA).

Thank you very much. 

p.s: I have asked in the issue https://github.com/devalab/DeepPocket/issues/26.
