### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by WangLiguo-DP** [devalab/DeepPocket#7]
when predicting binding sites given a .pdb file of a protein using:
python predict.py -p pdb/1alb_A.pdb -c first_model_fold1_best_test_auc_85001.pth.tar -s seg0_best_test_IOU_91.pth.tar -r 3

I meet this bug :
**'segmentation fault'**
after 
***** POCKET HUNTING BEGINS ***** 
***** POCKET HUNTING ENDS *****

I used gdb to view the core file :
'Failed to read a valid object file image from memory.
Core was generated by `python3 predict.py -p pdb/1alb_A.pdb -c first_model_fold1_best_test_auc_85001.p'.
Program terminated with signal 11, Segmentation fault.'

**Comment by RishalAggarwal** [comment]
Hey,

Could you share the PDB file to reproduce the error

**Comment by WangLiguo-DP** [comment]
OK，I used 1ALB_A in RCSB PDB, but I couldn't upload this pdb file in github issu, so upload the txt file instead
[1alb_A.txt](https://github.com/devalab/DeepPocket/files/8529715/1alb_A.txt)

**Comment by RishalAggarwal** [comment]
Hey sorry, it was a busy week. However, I am not able to reproduce the error, my best guess is that your environment may not be set for it.  If you just want the output files on this protein I have uploaded them here: https://drive.google.com/drive/folders/1G8-0Apxn7NEs7pnV0FPvUmQzY4s0vF4h?usp=sharing

**Comment by mainguyenanhvu** [comment]
Hello @WangLiguo-DP have you re-run data preparation for a custom data? If yes, please help me. 

I am trying to use the instruction to prepare data for training a new classifier. 
I have stuck in make_types step because I can't find train.txt and test.txt files. 

Moreover, I have 4 questions:
1. If I want to add several pdb files to the available scPDB dataset, how can I complete it?
2. The instruction for preparing data only works for a single pdb file, does it? If not, I need to write a pipeline to wrap up it. 
3. How to prepare train.txt and test.txt files to run make_types.py?
4. Could you please show me which file/folder needed inputting from previous to each step?

I am tried on [this pdb](https://www.rcsb.org/structure/8BRA).

Thank you very much. 

p.s: I have asked in the issue https://github.com/devalab/DeepPocket/issues/26.
